### PR TITLE
Required fields Google News

### PR DESCRIPTION
**Pull request by TomWalbers**
According to the documentation, there are some more required fields.
I added a couple of those fields.

Documentation I based myself on: https://support.google.com/news/publisher/answer/74288?hl=en

### CODE REVIEW

**Comment by berjanjonker** [comment]
@mkurz Can you approve this pull request and make a new release? The current GoogleNewsSitemap is outdated and therefore useless.

**Comment by mkurz** [comment]
I will have a look but I am very very busy right now. Maybe send me a reminder in like two weeks or so.
Can you also check the pull request if it is ok?

**Comment by berjanjonker** [comment]
@mkurz 
> Maybe send me a reminder in like two weeks or so

Can you approve this pull request and make a new release?

**Comment by mkurz** [comment]
@berjanjonker I hope I will find time soon for this pull request, sorry I am very busy right  now.

**Comment by mkurz** [comment]
Fixed via 1ceac7f3f079231d8ac511091102f5ff290e7dc5

**Comment by mkurz** [comment]
Version 1.1.0 containing this fix should be available in a few hours.

**Pull request closed without merging**
