### PR TITLE
adding support for custom suffices for sitemap generation

### PR DESCRIPTION
**Pull request by anellimarla**
Please review the latest. I have made sure indentation is fixed.

### CODE REVIEW

**Comment by anellimarla** [comment]
@dfabulich please approve the PR once reviewed so we can merge it. 

Thank you!
Ankita

**Comment by anellimarla** [comment]
Hi @dfabulich , please review the PR once you get a chance. its really important and I am waiting for your approval. Need this feature for something urgent. 

Thank you! 
Ankita

**Comment by dfabulich** [comment]
I rewrote your commit to avoid changing a bunch of irrelevant whitespace, and merged it. https://github.com/dfabulich/sitemapgen4j/commit/be330d6ec32ed50ce39c2041c233e7b9856235ee

Thanks for your contribution!

**Comment by anellimarla** [comment]
Hi thank you for merging the code. however we cannot use it in our code base as you have not released a version for gradle / maven 

This is what we use to pull your library as of now, 
 compile "com.google.code:sitemapgen4j:1.0.1"

We need a new version that has this change. Can you please deploy the latest ?

Thank you so so much! 
Ankita

**Pull request closed without merging**
