### PR TITLE
Google image extension

### PR DESCRIPTION
**Pull request by ThorKarlsson**
…gs to a single URL entry #42

### CODE REVIEW

**Comment by ThorKarlsson** [comment]
This PR adds support for images within extended sitemaps allowing you to up to 1000 image tags on a single URL. 
See 
[https://support.google.com/webmasters/answer/178636?hl=en](url)
and
[https://support.google.com/webmasters/answer/183668](url)

**Comment by mkurz** [comment]
Thanks, I will have a look at this as soon I find time.

**Comment by mkurz** [comment]
@ThorKarlsson thanks and sorry for the delay. I updated your pull request, changed the names of the classes and some comments.

**Comment by mkurz** [comment]
BTW: In your first commit you had a TODO:
```
TODO Add support for video tags and news tags
```
This is done already, see `GoogleVideoSitemapGenerator` and `GoogleNewsSitemapGenerator` classes.

**Comment by mkurz** [comment]
1.1.2 released, should be available soon.

**Pull request merged**
