### PR TITLE
update siteindex.xsd and sitemap.xsd

### PR DESCRIPTION
**Pull request by jiwhiz**
fix https://github.com/dfabulich/sitemapgen4j/issues/7

### CODE REVIEW

**Comment by mkurz** [comment]
@dfabulich Could you please review this PR? Thanks!

**Comment by mkurz** [comment]
@dfabulich Can we release `1.0.3` with the latest changes? I could do that if you are OK with it.

**Comment by dfabulich** [comment]
Go ahead, but I predict we'll want to want to do another release when we merge in the writeAsString patch, so if it's any trouble, you may want to hold off.

**Comment by mkurz** [comment]
No problem, I can wait.

**Comment by mkurz** [comment]
@jiwhiz Your change has been included in todays [v1.0.3 release](https://github.com/dfabulich/sitemapgen4j/releases/tag/v1.0.3).

**Pull request merged**
